# Netlify Configuration for Telefire México

[build]
  # Directory to publish (build output)
  publish = "dist/"
  
  # Build command - only build frontend for static hosting
  command = "vite build"
  
  # Functions directory (if needed)
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Production environment
  NODE_ENV = "production"

# Redirect rules for Single Page Application
# Note: API routes are not available in static hosting
# For backend functionality, consider Netlify Functions or external API

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache control for static assets
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Forms handling (if using Netlify Forms)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Context-specific builds
[context.production.environment]
  NODE_ENV = "production"
  VITE_APP_TITLE = "Telefire México - Sistemas de Detección y Prevención de Incendios"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"

# Plugin configuration - removed for simpler deployment
# [[plugins]]
#   package = "@netlify/plugin-lighthouse"